name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        project:
          - AdventOfCSharp.Tests/AdventOfCSharp.Tests
          - AdventOfCSharp.ProblemSolutionTests/AdventOfCSharp.ProblemSolutionTests
          - AdventOfCSharp.AnalyzerTests/AdventOfCSharp.Analyzers.Tests
          - AdventOfCSharp.CodeFixes.Tests/AdventOfCSharp.CodeFixes.Tests
          - AdventOfCSharp.SourceGenerators.Tests/AdventOfCSharp.SourceGenerators.Tests

    steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Tests in Project
      run: dotnet test ${{ project }}.csproj
